docs: fix toc slugify

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -4,6 +4,22 @@
 
 version: 2
 
+build:
+  jobs:
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/master -- docs/ mkdocs.yml .readthedocs.yaml;
+        then
+          exit 183;
+        fi
+    pre_build:
+      # Workaround for https://github.com/readthedocs/readthedocs.org/issues/10013
+      - 'sed "0,/slugify: null/s//slugify: \!\!python\/object\/apply:pymdownx.slugs.slugify {kwds: {case: lower}}/" mkdocs.yml'
+
 python:
   version: "3.8"
   install:
